# Generated by Django 4.1.1 on 2023-03-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='free',
        ),
        migrations.RemoveField(
            model_name='book',
            name='paid',
        ),
        migrations.AddField(
            model_name='book',
            name='plan',
            field=models.CharField(default='free', max_length=100),
        ),
    ]
