# Generated by Django 4.1.1 on 2023-03-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_remove_book_free_remove_book_paid_book_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
