# Generated by Django 4.1.1 on 2023-02-28 08:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_masthead'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.AddField(
            model_name='piece',
            name='slug',
            field=models.SlugField(default='default-value'),
        ),
    ]
