# Generated by Django 4.1.1 on 2023-02-28 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poet_name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='Poets Photos')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.issue')),
            ],
        ),
    ]
