# Generated by Django 4.1.1 on 2023-02-28 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_poet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='home.category', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='home.issue'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poets', to='home.issue'),
        ),
    ]
