# Generated by Django 4.1.1 on 2023-03-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_piece_featured_piece_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True, default='uu'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
