# Generated by Django 4.1.1 on 2023-03-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_issue_slug_alter_news_slug_alter_piece_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
