# Generated by Django 4.1.1 on 2023-03-02 15:58

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_number', models.CharField(max_length=200)),
                ('issue_title', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField()),
                ('issue_cover', models.ImageField(upload_to='Noise Issue Cover')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('author_bio', tinymce.models.HTMLField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noise.issue')),
            ],
        ),
    ]
