# Generated by Django 4.1.1 on 2023-03-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noise', '0003_alter_issue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='noise.issue'),
        ),
    ]
