# Generated by Django 4.1.1 on 2023-03-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noise', '0005_issue_cover_anotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['-publication_date']},
        ),
    ]
