# Generated by Django 4.1.1 on 2023-03-04 21:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('noise', '0006_alter_issue_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_title', models.CharField(max_length=200)),
                ('theme_exposition', tinymce.models.HTMLField()),
                ('guidelines', tinymce.models.HTMLField()),
                ('about_noise', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Submission',
            },
        ),
    ]
